### ISSUE TITLE
Better Animal Cape 

### ISSUE THREAD

**Issue by ardissaps** [Fourmisain/DyeAllTheThings#3]
Hello sir, how do you? :p
Inventory item works but when worn the color does not change.
https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus
![image](https://user-images.githubusercontent.com/82106625/180139850-1c3bbe19-072a-418d-91ca-323092678b49.png)
1.18.2
Thank you very much. :)

**Comment by Fourmisain** [comment]
Implemented in 1.3!

**Comment by ardissaps** [comment]
Thank you !
